import type { Metadata } from "next";
import "../../public/assets/css/bootstrap.min.css";
import "../../public/assets/css/bootstrap-icons.css";
import "../../public/assets/css/animate.min.css";
import "../../public/assets/css/swiper-bundle.min.css";
import "react-modal-video/css/modal-video.css";
import "../../public/assets/css/nice-select.css";
import "../../public/assets/css/style.css";
import { dmsans, manrope } from "../fonts/font";
import ClientRoot from "@/components/ClientRoot";
import ChunkErrorBoundary from "@/components/ChunkErrorBoundary";

export const metadata: Metadata = {
  title: "Kavalakat - Factory & Industry Website.",
  description: "Generated by Mindstory",
  icons: {
    icon: "/assets/new-images/fav-1.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className={`tt-magic-cursor ${dmsans.variable} ${manrope.variable}`} lang="en">
      <body>
        <ChunkErrorBoundary>
          <ClientRoot>
            {children}
          </ClientRoot>
        </ChunkErrorBoundary>
      </body>
    </html>
  );
}